import type { FormSchema } from "./types";

const yesNo = [
  { value: "ya", label: "Ya" },
  { value: "tidak", label: "Tidak" },
];

const activePassive = [
  { value: "aktif", label: "Aktif" },
  { value: "pasif", label: "Pasif" },
];

export const assessmentSchema: FormSchema = {
  schemaVersion: 1,
  title: "Assessment Kemampuan dan Kemauan Belajar Pasien dan Keluarga",
  shortTitle: "Assessment Edukasi Pasien",
  description:
    "Pemetaan kebutuhan, hambatan, dan metode edukasi yang sesuai untuk pasien serta keluarga.",
  sections: [
    {
      id: "readiness",
      eyebrow: "Bagian 01",
      title: "Kesiapan dan komunikasi",
      description:
        "Kenali nilai, kesiapan, bahasa, dan kebutuhan komunikasi pasien sebelum edukasi dimulai.",
      fields: [
        {
          id: "culturalBarrier",
          number: "01",
          type: "singleChoice",
          label: "Keyakinan dan nilai budaya pasien dan keluarga",
          description: "Apakah terdapat hambatan yang perlu diperhatikan?",
          required: true,
          options: [
            { value: "ada", label: "Ada hambatan" },
            { value: "tidak", label: "Tidak ada hambatan" },
          ],
        },
        {
          id: "culturalBarrierDetails",
          type: "textarea",
          label: "Jelaskan hambatan keyakinan atau budaya",
          placeholder: "Tuliskan hambatan yang perlu diperhatikan…",
          required: true,
          visibleWhen: { fieldId: "culturalBarrier", operator: "equals", value: "ada" },
        },
        {
          id: "educationReadiness",
          number: "02",
          type: "singleChoice",
          label: "Kesediaan pasien dan keluarga untuk menerima edukasi",
          required: true,
          options: [
            { value: "bersedia", label: "Bersedia" },
            { value: "tidak", label: "Tidak bersedia" },
          ],
        },
        {
          id: "educationRefusalReason",
          type: "textarea",
          label: "Alasan tidak bersedia",
          placeholder: "Tuliskan alasan pasien atau keluarga…",
          required: true,
          visibleWhen: { fieldId: "educationReadiness", operator: "equals", value: "tidak" },
        },
        {
          id: "languages",
          number: "03",
          type: "multiChoice",
          label: "Bahasa sehari-hari",
          description: "Pilih semua bahasa yang digunakan.",
          required: true,
          minSelections: 1,
          options: [
            { value: "indonesia", label: "Bahasa Indonesia" },
            { value: "inggris", label: "Bahasa Inggris" },
            { value: "daerah", label: "Bahasa daerah" },
            { value: "lain", label: "Bahasa lain" },
          ],
        },
        {
          id: "languageFluency",
          type: "matrixSingle",
          label: "Kemampuan penggunaan bahasa",
          description: "Tentukan kemampuan aktif atau pasif untuk setiap bahasa yang dipilih.",
          required: true,
          minSelections: 1,
          rowsFromField: "languages",
          rows: [
            { value: "indonesia", label: "Bahasa Indonesia" },
            { value: "inggris", label: "Bahasa Inggris" },
            { value: "daerah", label: "Bahasa daerah" },
            { value: "lain", label: "Bahasa lain" },
          ],
          columns: activePassive,
        },
        {
          id: "regionalLanguage",
          type: "text",
          label: "Nama bahasa daerah",
          placeholder: "Contoh: Bali, Sasak, Bugis",
          required: true,
          visibleWhen: { fieldId: "languages", operator: "includes", value: "daerah" },
        },
        {
          id: "otherLanguage",
          type: "text",
          label: "Nama bahasa lain",
          placeholder: "Tuliskan bahasa lainnya",
          required: true,
          visibleWhen: { fieldId: "languages", operator: "includes", value: "lain" },
        },
        {
          id: "needsInterpreter",
          number: "04",
          type: "singleChoice",
          label: "Perlu penerjemah bahasa atau bahasa isyarat",
          required: true,
          options: yesNo,
        },
        {
          id: "interpreterLanguage",
          type: "text",
          label: "Bahasa yang dibutuhkan",
          placeholder: "Tuliskan bahasa penerjemah",
          required: true,
          visibleWhen: { fieldId: "needsInterpreter", operator: "equals", value: "ya" },
        },
      ],
    },
    {
      id: "ability",
      eyebrow: "Bagian 02",
      title: "Kemampuan belajar",
      description: "Catat latar pendidikan, kemampuan membaca, dan hambatan belajar pasien.",
      fields: [
        {
          id: "educationLevel",
          number: "05",
          type: "singleChoice",
          label: "Tingkat pendidikan",
          required: true,
          options: [
            { value: "sd", label: "SD" },
            { value: "smp", label: "SMP" },
            { value: "sma", label: "SMA" },
            { value: "akademi", label: "Akademi" },
            { value: "sarjana", label: "Sarjana" },
            { value: "lain", label: "Lain-lain" },
          ],
        },
        {
          id: "otherEducationLevel",
          type: "text",
          label: "Pendidikan lainnya",
          required: true,
          visibleWhen: { fieldId: "educationLevel", operator: "equals", value: "lain" },
        },
        {
          id: "canRead",
          number: "06",
          type: "singleChoice",
          label: "Kemampuan membaca",
          required: true,
          options: [
            { value: "bisa", label: "Bisa" },
            { value: "tidak", label: "Tidak" },
          ],
        },
        {
          id: "emotionalBarriers",
          number: "07",
          type: "multiChoice",
          label: "Hambatan emosional atau motivasi",
          description: "Pilih semua yang sesuai.",
          required: true,
          minSelections: 1,
          exclusiveValues: ["tidak_ada"],
          options: [
            { value: "tidak_ada", label: "Tidak ada" },
            { value: "takut_panik", label: "Takut / panik" },
            { value: "tidak_tertarik", label: "Tidak tertarik" },
            { value: "tidak_nyaman", label: "Tidak nyaman" },
            { value: "hambatan_bahasa", label: "Hambatan bahasa" },
          ],
        },
        {
          id: "physicalCognitiveBarriers",
          number: "08",
          type: "multiChoice",
          label: "Hambatan fisik dan kognitif",
          description: "Pilih semua yang sesuai.",
          required: true,
          minSelections: 1,
          exclusiveValues: ["tidak_ada"],
          options: [
            { value: "tidak_ada", label: "Tidak ada" },
            { value: "penglihatan", label: "Gangguan penglihatan" },
            { value: "pendengaran", label: "Gangguan pendengaran" },
            { value: "kognitif", label: "Gangguan kognitif" },
          ],
        },
      ],
    },
    {
      id: "education-plan",
      eyebrow: "Bagian 03",
      title: "Rencana edukasi",
      description: "Tentukan kebutuhan, metode, dan unit yang perlu berkoordinasi.",
      fields: [
        {
          id: "educationNeeds",
          number: "09",
          type: "multiChoice",
          label: "Kebutuhan edukasi",
          required: true,
          minSelections: 1,
          options: [
            { value: "diagnosis_penyakit", label: "Diagnosis dan penyakit" },
            { value: "farmasi", label: "Farmasi" },
            { value: "asuhan_keperawatan", label: "Asuhan keperawatan" },
            { value: "konseling_gizi", label: "Konseling gizi" },
          ],
        },
        {
          id: "preferredMethods",
          number: "10",
          type: "multiChoice",
          label: "Metode yang disukai",
          required: true,
          minSelections: 1,
          options: [
            { value: "demonstrasi", label: "Demonstrasi" },
            { value: "audio_visual", label: "Audio visual / gambar" },
            { value: "diskusi", label: "Diskusi" },
            { value: "video", label: "Video" },
            { value: "flip_chart", label: "Flip chart" },
            { value: "leaflet", label: "Leaflet" },
          ],
        },
        {
          id: "coordinationUnits",
          number: "11",
          type: "multiChoice",
          label: "Koordinasi edukasi dengan unit",
          required: true,
          minSelections: 1,
          options: [
            { value: "dpjp", label: "DPJP" },
            { value: "perawat", label: "Perawat" },
            { value: "farmasi", label: "Farmasi" },
            { value: "gizi", label: "Gizi" },
            { value: "fisioterapi", label: "Fisioterapi" },
          ],
        },
      ],
    },
  ],
};
